# Generated by Django 5.1.3 on 2024-11-18 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='id_number',
        ),
    ]
